### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-rpc-api#15]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by jim-krueger** [comment]
Awaiting version information for javax.servlet before I can close.

**Comment by m0mus** [comment]
Servlet API 4.0.2 has been released: https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker

You can proceed.
