### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-rpc-api#26]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by kwsutter** [comment]
JAX-RPC-API has previously been released to Maven:  https://mvnrepository.com/artifact/jakarta.xml.rpc/jakarta.xml.rpc-api/1.1.3
