### ISSUE TITLE
Prepare XML RPC project for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-rpc-api#28]
### Tasks

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by starksm64** [comment]
Working on updating text files

**Comment by m0mus** [comment]
jakartaee/specifications PRs: 
https://github.com/jakartaee/specifications/pull/67
https://github.com/jakartaee/specifications/pull/68

Staging release:
https://oss.sonatype.org/content/repositories/staging/jakarta/xml/rpc/jakarta.xml.rpc-api/1.1.4/
