### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-rpc-api#5]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by kwsutter** [comment]
Will be working with Jim Krueger to get these pipelines done for the Stable API project.   Still waiting for Jim's committership to come through...

**Comment by jim-krueger** [comment]
Jenkins Build CI/CD pipeline (first pass) is created (awaiting GPG and OSSRH Setup). I also may need to adjust the maven commands and there seems to be a versioning issue as well that I'll need to address:

https://jenkins.eclipse.org/jakartaee-stable/job/JAX-RPC-API%20master%20build/    (master build)
https://jenkins.eclipse.org/jakartaee-stable/job/JAX-RPC-API_EE4J_build/                   (ee4j_8 build)

**Comment by jim-krueger** [comment]
Jenkin CI/CD build pipelines are green. Closing issue:

https://jenkins.eclipse.org/jakartaee-stable/job/JAX-RPC-API%20master%20build/
https://jenkins.eclipse.org/jakartaee-stable/job/JAX-RPC-API_EE4J_8_build/
