### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-rpc-api#6]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)
- [Release job on the new cloud infra](https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job)

**Comment by kwsutter** [comment]
Will be working with Jim Krueger to get these pipelines done for the Stable API project.   Still waiting for Jim's committership to come through...

**Comment by m0mus** [comment]
@jim-krueger I see that build job has been created and works fine for this project:
https://jenkins.eclipse.org/jakartaee-stable/job/JAX-RPC-API_EE4J_8_build/
Can this task be closed?

**Comment by jim-krueger** [comment]
The job itself is correct,  but does not execute cleanly so I will leave this open:
https://jenkins.eclipse.org/jakartaee-stable/job/JAX-RPC-Release/

**Comment by senivam** [comment]
Release job:
https://jenkins.eclipse.org/jakartaee-stable/job/JAX-RPC-Release_pipeline/
[pipeline version]

**Comment by Tomas-Kraus** [comment]
I fixed the job. You can close it now.

**Comment by jim-krueger** [comment]
@senivam There was a release pipline job existing there already that is identical to the one you added, so I will remove the one you added.

**Comment by senivam** [comment]
except the one which exists is not pipeline but batch. I've added pipeline which was intended to be used as Jenkins_release file from SCM (recommended job style by Eclipse). However if it is not required delete it is the best option.

**Comment by jim-krueger** [comment]
@senivam My mistake.   They were not identical and therefore I've added your's back in.

**Comment by jim-krueger** [comment]
@senivam  I will likely change my other jobs to match yours.  I was following the pattern sent out for us to use which apparently was freestyle, not pipeline.

**Comment by jim-krueger** [comment]
@senivam The job you added appears to fail if run multiple times :  [Pipeline] End of Pipeline
ERROR: origin/1.1.3 branch already exists
Finished: FAILURE

**Comment by senivam** [comment]
@jim-krueger thank you for testing it. Yes, there was a mistake inside (OVERWRITE did not work correctly, I've fixed that).
Regarding the pipeline script itself - my intention was to:
prepare the script of the pipeline directly inside the job (test and try it), 

than do a pull request for that script (it is #19 with OVERWRITE fixes included). 

And after the PR is accepted in the job it is possible to change definition of pipeline from 'pipeline script' to 'Pipeline script from SCM' and indicate the path to the merged script (Jenkinsfile) directly in the jax-rpc-api project at github. 

After that it is not required to maintain the job at all, but only perform changes to the script inside the project (if any changes are required). Further more the job script would be stored in SCM so it wont be lost for some reason (if Jenkins job is deleted or something).

**Comment by jim-krueger** [comment]
@senivam  Thanks for the explanation.  I have approved and merged #19.

**Comment by senivam** [comment]
Thank you @jim-krueger, I've modified the job to take script from SCM (and run it to test if it works).

**Comment by jim-krueger** [comment]
@senivam Looking at your pipeline I see you have "Branches to build" with "*/master".  Do you also need to add a branch for "*/EE4J_8"?

**Comment by senivam** [comment]
@jim-krueger This refers only to place from where the script itself is taken. So, it is located in jax-rpc-api , branch master. Later for sure it could be merged into EE4J_8 or some other branch but this does not reflect its existence in master and jenkins' job takes it only from master (any other script's duplicates in other branches are not counted).

Then when script is grabbed from master it starts and it has its own parameters, so it uses BRANCH parameter to determine which branch shall be released it is not relevant to script's location. Furthermore the script itself could be in another repository, forked from jax-rpc-api for example, but it works on main jax-rpc-api repository and uses predefined set of parameters to determine what to do. 

So, in general, script is taken from one place and works on another, occasionally (or intentionally) they are the same :)
